import json
import logging
from datetime import date

from odoo import http
from odoo.http import request, content_disposition
from odoo.exceptions import AccessError, UserError

from odoo.addons.purchase_advanced_analytics.reports.purchase_excel_report import PurchaseExcelReport

_logger = logging.getLogger(__name__)


class PurchaseAnalyticsController(http.Controller):

    @http.route(
        '/purchase_advanced_analytics/xlsx/<int:wizard_id>',
        type='http',
        auth='user',
        methods=['GET'],
    )
    def download_excel_report(self, wizard_id, **kwargs):
        """Download a Purchase Analytics Excel report for the given wizard record.

        Steps:
        1. Verify the current user belongs to the Purchase Analytics User group.
        2. Browse the wizard record and confirm it exists.
        3. Confirm the wizard belongs to a company accessible by the current user.
        4. Build filters from the wizard and generate the XLSX workbook.
        5. Return the file as an HTTP response.

        Error handling:
        - AccessError  → 403 JSON response
        - UserError    → 400 JSON response
        - Any other    → 500 JSON response
        """
        try:
            # ------------------------------------------------------------------
            # 1. Group check
            # ------------------------------------------------------------------
            if not request.env.user.has_group(
                'purchase_advanced_analytics.group_purchase_analytics_user'
            ):
                raise AccessError(
                    "You do not have permission to download Purchase Analytics reports."
                )

            # ------------------------------------------------------------------
            # 2. Load the wizard record
            # ------------------------------------------------------------------
            env = request.env
            wizard = env['purchase.analytics.report.wizard'].browse(wizard_id)

            if not wizard.exists():
                raise UserError(
                    f"Report wizard with id {wizard_id} does not exist or has expired."
                )

            # ------------------------------------------------------------------
            # 3. Company safety check
            # ------------------------------------------------------------------
            # TransientModel records carry the company of the user who created them
            # via the ORM's create_uid.  We verify that the creating user's company
            # is among the companies accessible to the current user so that one
            # user cannot download another company's report simply by guessing an id.
            accessible_company_ids = env.user.company_ids.ids
            wizard_company_id = wizard.create_uid.company_id.id
            if wizard_company_id and wizard_company_id not in accessible_company_ids:
                raise AccessError(
                    "The requested report belongs to a company you do not have access to."
                )

            # Additionally restrict browsing to the wizard owner to prevent
            # lateral access between users of the same company.
            if wizard.create_uid.id != env.uid:
                raise AccessError(
                    "You are not allowed to download a report generated by another user."
                )

            # ------------------------------------------------------------------
            # 4. Build filters and generate workbook bytes
            # ------------------------------------------------------------------
            filters = wizard._build_filters()

            report = PurchaseExcelReport(env, filters, wizard)
            content = report.generate()

            # ------------------------------------------------------------------
            # 5. Build a meaningful filename and return the file response
            # ------------------------------------------------------------------
            report_type = (wizard.report_type or 'report').replace(' ', '_')
            today_str = date.today().strftime('%Y%m%d')
            filename = f"purchase_analytics_{report_type}_{today_str}.xlsx"

            headers = [
                (
                    'Content-Type',
                    'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
                ),
                ('Content-Disposition', content_disposition(filename)),
            ]
            return request.make_response(content, headers=headers)

        # ------------------------------------------------------------------
        # Error handling
        # ------------------------------------------------------------------
        except AccessError as exc:
            _logger.warning(
                "Purchase Analytics – access denied for wizard %s: %s",
                wizard_id,
                exc,
            )
            body = json.dumps({'error': 'Access Denied', 'message': str(exc)})
            return request.make_response(
                body,
                status=403,
                headers=[('Content-Type', 'application/json')],
            )

        except UserError as exc:
            _logger.warning(
                "Purchase Analytics – user error for wizard %s: %s",
                wizard_id,
                exc,
            )
            body = json.dumps({'error': 'Bad Request', 'message': str(exc)})
            return request.make_response(
                body,
                status=400,
                headers=[('Content-Type', 'application/json')],
            )

        except Exception as exc:  # pylint: disable=broad-except
            _logger.exception(
                "Purchase Analytics – unexpected error generating report for wizard %s",
                wizard_id,
            )
            body = json.dumps(
                {
                    'error': 'Internal Server Error',
                    'message': 'An unexpected error occurred while generating the report.',
                }
            )
            return request.make_response(
                body,
                status=500,
                headers=[('Content-Type', 'application/json')],
            )
